---

name: Build and publish Docker image

env:
  POSTGRES_VERSION: "15.6"
  PGVECTOR_VERSION: "0.5.1"

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (maybe) publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            POSTGRES_VERSION=${{env.POSTGRES_VERSION}}
            PGVECTOR_VERSION=${{env.PGVECTOR_VERSION}}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/zapgram/pilot-postgres:${{env.POSTGRES_VERSION}}-pgvector${{env.PGVECTOR_VERSION}}
          push: ${{ github.ref_name == 'trunk' }}
